# Site settings
author: Bernard  Mel
title: 
header-img: img/home-bg.png
email: bernard.mamuyac@gmail.com
copyright_name: Bernard  Mel
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Bernard_Mel
github_username:  bernardmel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
